#ifndef UTILITIES_H
#define UTILITIES_H

#ifndef DEFAULT_WINDOW_WIDTH
#define DEFAULT_WINDOW_WIDTH 640
#endif

#ifndef DEFAULT_WINDOW_HEIGHT
#define DEFAULT_WINDOW_HEIGHT 480
#endif

enum GAMESTATE {MAINMENU, OPTIONSMENU, PLAYING, CLOSE};

#endif